=== mikechabot/AnotherGlass/web/WEB-INF/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="configuration" type="configuration" />

	<xs:element name="databaseConfiguration" type="databaseConfiguration" />

	<xs:element name="wineApiConfiguration" type="wineApiConfiguration" />

	<xs:complexType name="configuration">
		<xs:sequence>
			<xs:element name="mode" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="dev" />
						<xs:enumeration value="test" />
						<xs:enumeration value="prod" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="database" type="databaseConfiguration"
				nillable="false" minOccurs="3" maxOccurs="3" />
			<xs:element name="wineApi" type="wineApiConfiguration"
				minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="databaseConfiguration">
		<xs:sequence>
			<xs:element name="mode" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="dev" />
						<xs:enumeration value="test" />
						<xs:enumeration value="prod" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="driver" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="url" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="username" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="password" type="xs:string" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="wineApiConfiguration">
		<xs:sequence>
			<xs:element name="url" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="key" type="xs:string" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="fetchSize" type="xs:long" />
			<xs:element name="fetchOffset" type="xs:long" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== mikechabot/AnotherGlass/web/WEB-INF/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd">
	<mode>dev</mode>
	<adminPassword>admin</adminPassword>
	<database>
		<mode>dev</mode>
		<driver>org.postgresql.Driver</driver>
		<url>jdbc:postgresql://localhost:5432/dev</url>
		<username>anotherglass</username>
		<password>anotherglass</password>
	</database>
	<database>
		<mode>test</mode>
		<driver>org.postgresql.Driver</driver>
		<url>jdbc:postgresql://localhost:5432/test</url>
		<username>anotherglass</username>
		<password>anotherglass</password>
	</database>
	<database>
		<mode>prod</mode>
		<driver>org.postgresql.Driver</driver>
		<url>jdbc:postgresql://localhost:5432/prod</url>
		<username>anotherglass</username>
		<password>anotherglass</password>
	</database>
	<wineApi>
		<url>http://services.wine.com/api/beta2/service.svc/json/</url>
		<key>b77c34d4cc093ccc98977db8e10c7e85</key>
		<fetchSize>300</fetchSize>
		<fetchOffset>66800</fetchOffset>
	</wineApi>
</configuration>
